import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('data/ai_vs_human_text_2026.csv')
print(df.shape)
print(df['label'].value_counts(normalize=True))
fig, axes = plt.subplots(2, 2, figsize=(12, 9))
sns.countplot(data=df, x='label', ax=axes[0,0], hue='label', palette='Set2', legend=False)
axes[0,0].set_title('Label Distribution (Class Imbalance)')
ct = pd.crosstab(df['domain'], df['label'])
ct.plot(kind='bar', stacked=True, ax=axes[0,1], color=['#4C72B0','#DD8452'])
axes[0,1].set_title('Label Count by Domain')
axes[0,1].tick_params(axis='x', rotation=0)
sns.boxplot(data=df, x='domain', y='word_count', hue='label', ax=axes[1,0], palette='Set2')
axes[1,0].set_title('Word Count by Domain and Label')
sns.boxplot(data=df, x='domain', y='avg_sentence_length', hue='label', ax=axes[1,1], palette='Set2')
axes[1,1].set_title('Avg Sentence Length by Domain and Label')
plt.tight_layout()
plt.savefig('outputs/figures/eda_overview.png', dpi=130)
plt.close()
dup_count = df.duplicated(subset=['text_content']).sum()
dup_by_label = df[df.duplicated(subset=['text_content'], keep=False)].groupby('label').size()
print('duplicate rows:', dup_count)
print(dup_by_label)
fig, ax = plt.subplots(figsize=(7,5))
sns.barplot(x=['Unique', 'Duplicated'], y=[2000-len(df[df.duplicated(subset=['text_content'], keep=False)]), len(df[df.duplicated(subset=['text_content'], keep=False)])], ax=ax, palette='Set2')
ax.set_title('Template Leakage Risk: Unique vs Duplicated text_content')
plt.tight_layout()
plt.savefig('outputs/figures/duplicate_risk.png', dpi=130)
plt.close()
summary = df.groupby(['domain','label']).agg(n=('text_id','count'), avg_words=('word_count','mean'), avg_sent_len=('avg_sentence_length','mean')).round(1)
print(summary)
summary.to_csv('outputs/figures/domain_label_summary.csv')
print(df['topic_hint'].nunique())
print(df.groupby('label')['topic_hint'].nunique())